from models.mood_analyzer import MoodAnalyzer
from backend.spotify_client import SpotifyClient
from backend.itunes_client import ITunesClient

MOOD_PLAYLIST_NAMES = {
    "happy":     "Phoenix Happy Vibes",
    "sad":       "Phoenix Sad Hours",
    "energetic": "Phoenix Energy Boost",
    "chill":     "Phoenix Chill Zone",
}

MOOD_DESCRIPTIONS = {
    "happy":     "Upbeat tracks to keep your mood soaring - auto-generated by PhoenixPlaylist.",
    "sad":       "Melancholic melodies for reflective moments - auto-generated by PhoenixPlaylist.",
    "energetic": "High-energy bangers to power your workout - auto-generated by PhoenixPlaylist.",
    "chill":     "Relaxed, easy-listening tracks to unwind - auto-generated by PhoenixPlaylist.",
}


class PlaylistManager:
    def __init__(self):
        self.mood_analyzer = MoodAnalyzer()
        self.spotify = SpotifyClient()
        self.itunes  = ITunesClient()

    def recognize_and_classify(self, query: str) -> dict:
        """
        Search iTunes for a track, run mood analysis using
        VADER on the track name + genre-based feature estimation.
        """
        track = self.itunes.search_track(query)
        if not track:
            return {"error": f"No track found for: {query}"}

        mood_result = self.mood_analyzer.analyze(
            text=track.get("name", ""),
            audio_features=None,
            genre=track.get("genre"),
        )

        return {
            "track":          track,
            "audio_features": {"energy": mood_result.energy, "valence": mood_result.valence},
            "mood":           mood_result.to_dict(),
        }

    def build_mood_playlist(self, queries: list[str], mood_filter: str | None = None) -> dict:
        classified: dict[str, list] = {m: [] for m in MOOD_PLAYLIST_NAMES}

        for query in queries:
            try:
                result = self.recognize_and_classify(query)
                if "error" in result:
                    continue
                mood = result["mood"]["mood"]
                classified[mood].append(result)
            except Exception as e:
                classified.setdefault("errors", []).append({"query": query, "error": str(e)})

        if mood_filter and mood_filter in classified:
            return {mood_filter: classified[mood_filter]}
        return classified

    def push_mood_playlist_to_spotify(self, tracks: list[dict], mood: str) -> dict:
        """
        Create a Spotify playlist for the given mood. For each track,
        attempt to resolve its Spotify URI via Spotify search. If Spotify
        search is unavailable, the playlist is still created and the song
        list is included in the description so the user has a record.
        """
        user    = self.spotify.get_current_user()
        user_id = user["id"]

        # Try to resolve each iTunes track to a Spotify URI
        uris   = []
        failed = []
        for t in tracks:
            track_meta = t.get("track") or {}
            query = f"{track_meta.get('name', '')} {track_meta.get('artist', '')}".strip()
            if not query:
                continue
            try:
                spotify_track = self.spotify.search_track(query)
                if spotify_track and spotify_track.get("uri"):
                    uris.append(spotify_track["uri"])
                else:
                    failed.append(query)
            except Exception:
                failed.append(query)

        description = MOOD_DESCRIPTIONS.get(mood, "Auto-generated by PhoenixPlaylist.")
        if failed and not uris:
            # If Spotify search is completely unavailable, embed song list in description
            preview = ", ".join(failed[:10])
            description = f"{description} Songs: {preview}"

        playlist = self.spotify.create_playlist(
            user_id,
            MOOD_PLAYLIST_NAMES.get(mood, f"Phoenix {mood.capitalize()} Playlist"),
            description,
        )

        if uris:
            self.spotify.add_tracks_to_playlist(playlist["id"], uris)

        return {
            "playlist_id":   playlist["id"],
            "playlist_url":  playlist["external_urls"]["spotify"],
            "name":          playlist["name"],
            "tracks_added":  len(uris),
            "tracks_failed": len(failed),
        }
