from models.mood_analyzer import MoodAnalyzer
from backend.spotify_client import SpotifyClient

MOOD_PLAYLIST_NAMES = {
    "happy":     "Phoenix Happy Vibes",
    "sad":       "Phoenix Sad Hours",
    "energetic": "Phoenix Energy Boost",
    "chill":     "Phoenix Chill Zone",
}

MOOD_DESCRIPTIONS = {
    "happy":     "Upbeat tracks to keep your mood soaring — auto-generated by PhoenixPlaylist.",
    "sad":       "Melancholic melodies for reflective moments — auto-generated by PhoenixPlaylist.",
    "energetic": "High-energy bangers to power your workout — auto-generated by PhoenixPlaylist.",
    "chill":     "Relaxed, easy-listening tracks to unwind — auto-generated by PhoenixPlaylist.",
}


class PlaylistManager:
    def __init__(self):
        self.mood_analyzer = MoodAnalyzer()
        self.spotify = SpotifyClient()

    def recognize_and_classify(self, query: str) -> dict:
        """
        Search Spotify for a track, fetch its audio features,
        run mood analysis, and return a combined result dict.
        """
        track = self.spotify.search_track(query)
        if not track:
            return {"error": f"No track found for: {query}"}

        audio_features = None
        try:
            audio_features = self.spotify.get_audio_features(track["id"])
        except Exception:
            pass

        mood_result = self.mood_analyzer.analyze("", audio_features)

        return {
            "track":          track,
            "audio_features": audio_features,
            "mood":           mood_result.to_dict(),
        }

    def build_mood_playlist(self, queries: list[str], mood_filter: str | None = None) -> dict:
        """
        Classify a list of song queries into mood buckets.
        Returns { mood: [track_results] }.
        """
        classified: dict[str, list] = {m: [] for m in MOOD_PLAYLIST_NAMES}

        for query in queries:
            try:
                result = self.recognize_and_classify(query)
                if "error" in result:
                    continue
                mood = result["mood"]["mood"]
                classified[mood].append(result)
            except Exception as e:
                classified.setdefault("errors", []).append({"query": query, "error": str(e)})

        if mood_filter and mood_filter in classified:
            return {mood_filter: classified[mood_filter]}
        return classified

    def push_mood_playlist_to_spotify(self, tracks: list[dict], mood: str) -> dict:
        """
        Create a Spotify playlist for the given mood and add tracks to it.
        Requires an active user OAuth session.
        """
        user     = self.spotify.get_current_user()
        user_id  = user["id"]

        playlist = self.spotify.create_playlist(
            user_id,
            MOOD_PLAYLIST_NAMES.get(mood, f"Phoenix {mood.capitalize()} Playlist"),
            MOOD_DESCRIPTIONS.get(mood, "Auto-generated by PhoenixPlaylist."),
        )

        uris = [t["track"]["uri"] for t in tracks if t.get("track", {}).get("uri")]

        if uris:
            self.spotify.add_tracks_to_playlist(playlist["id"], uris)

        return {
            "playlist_id":  playlist["id"],
            "playlist_url": playlist["external_urls"]["spotify"],
            "name":         playlist["name"],
            "tracks_added": len(uris),
        }
