from models.mood_analyzer import MoodAnalyzer
from backend.spotify_client import SpotifyClient
from backend.shazam_client import ShazamClient

MOOD_PLAYLIST_NAMES = {
    "happy": "🌟 Phoenix Happy Vibes",
    "sad": "🌧️ Phoenix Sad Hours",
    "energetic": "⚡ Phoenix Energy Boost",
    "chill": "🍃 Phoenix Chill Zone",
}

MOOD_DESCRIPTIONS = {
    "happy": "Upbeat tracks to keep your mood soaring — auto-generated by PhoenixPlaylist.",
    "sad": "Melancholic melodies for reflective moments — auto-generated by PhoenixPlaylist.",
    "energetic": "High-energy bangers to power your workout — auto-generated by PhoenixPlaylist.",
    "chill": "Relaxed, easy-listening tracks to unwind — auto-generated by PhoenixPlaylist.",
}


class PlaylistManager:
    def __init__(self):
        self.mood_analyzer = MoodAnalyzer()
        self.spotify = SpotifyClient()
        self.shazam = ShazamClient()

    def recognize_and_classify(self, query: str) -> dict:
        """
        Search Shazam for a song, then enrich it with Spotify data and mood analysis.
        Returns a combined track dict.
        """
        shazam_track = self.shazam.search_song(query)
        if not shazam_track:
            return {"error": f"No track found for query: {query}"}

        spotify_track = self.spotify.search_track(
            shazam_track["title"], shazam_track["artist"]
        )

        audio_features = None
        if spotify_track:
            try:
                audio_features = self.spotify.get_audio_features(spotify_track["id"])
            except Exception:
                pass

        mood_result = self.mood_analyzer.analyze(
            shazam_track.get("lyrics_snippet", ""), audio_features
        )

        return {
            "shazam": shazam_track,
            "spotify": spotify_track,
            "audio_features": audio_features,
            "mood": mood_result.to_dict(),
        }

    def build_mood_playlist(self, queries: list[str], mood_filter: str | None = None) -> dict:
        """
        Given a list of song queries, classify each by mood, then group into
        mood buckets. If mood_filter is set, only return tracks matching that mood.
        Returns a dict of { mood: [tracks] }.
        """
        classified: dict[str, list] = {m: [] for m in MOOD_PLAYLIST_NAMES}

        for query in queries:
            try:
                result = self.recognize_and_classify(query)
                if "error" in result:
                    continue
                mood = result["mood"]["mood"]
                classified[mood].append(result)
            except Exception as e:
                classified.setdefault("errors", []).append({"query": query, "error": str(e)})

        if mood_filter and mood_filter in classified:
            return {mood_filter: classified[mood_filter]}
        return classified

    def push_mood_playlist_to_spotify(self, tracks: list[dict], mood: str) -> dict:
        """
        Create a Spotify playlist for a given mood and add the matched tracks to it.
        Requires active Spotify session.
        """
        user = self.spotify.get_current_user()
        user_id = user["id"]

        playlist = self.spotify.create_playlist(
            user_id,
            MOOD_PLAYLIST_NAMES.get(mood, f"Phoenix {mood.capitalize()} Playlist"),
            MOOD_DESCRIPTIONS.get(mood, "Auto-generated by PhoenixPlaylist."),
        )

        uris = [
            t["spotify"]["uri"]
            for t in tracks
            if t.get("spotify") and t["spotify"].get("uri")
        ]

        if uris:
            self.spotify.add_tracks_to_playlist(playlist["id"], uris)

        return {
            "playlist_id": playlist["id"],
            "playlist_url": playlist["external_urls"]["spotify"],
            "name": playlist["name"],
            "tracks_added": len(uris),
        }
